### ISSUE TITLE
ERROR: dependencies ‘genbankr’, ‘coRdon’ are not available for package ‘chloroplot’

### ISSUE THREAD

**Issue by pengfang11** [shuyuzheng/Chloroplot#1]
when I tried to install this package, it showed me that:
ERROR: dependencies ‘genbankr’, ‘coRdon’ are not available for package ‘chloroplot’
* removing ‘/ifs1/User/ziyuan/R/x86_64-redhat-linux-gnu-library/3.6/chloroplot’
Warning in install.packages :
  installation of package ‘/ifs1/User/ziyuan/pengfang/learning/pengfang11-Chloroplot-master/Chloroplot.tar.gz’ had non-zero exit status

**Comment by shuyuzheng** [comment]
"[coRdon](https://www.bioconductor.org/packages/release/bioc/html/coRdon.html)" and "[genbankr](https://www.bioconductor.org/packages/release/bioc/html/genbankr.html)" are [Bioconductor](https://www.bioconductor.org/) packages. You can install them with BiocManager:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(c("coRdon", "genbankr"))
```

**Comment by pengfang11** [comment]
thanks  so much for your answer. As in China I have to try to run the codes on my own computer, because we can't go to the website--https://irscope.shinyapps.io/Chloroplot/,  always get the information "Disconnected from the server". Would you please considering adding an example or give some help docoments? I only have some basic R knowledge, and so are my colleagues, we tried several times but can't get plots using this chloroplot package.

**Comment by shuyuzheng** [comment]
Hi PengFang,

 If you have successfully installed the package. There are only three functions you should use: "PlotTab", " PlotMitGenome"and "PlotPlastidGenome". Following are two examples for plotting mitochondrion and chloroplast genome

``` 
library(chloroplot)
# Plot Ppchloroplast genome.

# 1. Parsing the GenBank file.
#"EU549769" is the GenBank accession for Guizotia abyssinica chloroplast 
t <- PlotTab(gbfile = "EU549769")
# 2. Generate plot
PlotPlastidGenome(t) # The plot will be saved in a pdf file under your work directory.
PlotPlastidGenome(t, save = FALSE) # The plot will be shown in the "plot" panel if you are using Rstudio.

# Plot mitochondrion genome.

# 1. Parsing the GenBank file
# "NC_012920.1" is the GenBank accession for Homo sapiens mitochondrion
t <- PlotTab(gbfile = "NC_012920.1")
# 2. Generate plot
PlotMitGenome(t) # The plot will be saved in a pdf file under your work directory.
PlotMitGenome(t, save = FALSE) # The plot will be shown in the "plot" panel if you are using Rstudio.
```

For tuning the plots, you have to change the parameters of  " PlotMitGenome" and "PlotPlastidGenome" functions. You can get the documentation for them by calling:

```
?PlotMitGenome
?PlotPlastidGenome
```
in R console.
