### ISSUE TITLE
Possible bug in IR detection

### ISSUE THREAD

**Issue by ante-turudic** [shuyuzheng/Chloroplot#2]
In IRs detection (file detect_ir.R), there are checks does any of IRA or IRB cover start point. If start point is covered, sequence in shifted and procedure is repeated.

Code that handles it, for IRA part is (https://github.com/shuyuzheng/Chloroplot/blob/master/R/detect_ir.R#L31):
```
while(m$group[1] == 1){
  tick <- tick + seed.size
  genome <- c(genome[(l - tick + 1):l], genome[1:(l - tick)])
  ...
}
```
If while loop is executed `n` times, than tick is set to `seed.size * n`, but genome is shifted by `seed.size * n * (n+1) / 2` bp. That is due genome was already shifted by previous loops, and tick values are accumulated. One solution is to use two variables, like `original_genome` and `genome`. Or even simpler solution, to shift genome for `seed.size` bp:
```
genome <- c(genome[(l - seed.size + 1):l], genome[1:(l - seed.size)])
```

Similar is for IRB check, line 41:
```
genome <- c(genome[(- tick + 1):l], genome[1: -tick])
```
->
```
genome <- c(genome[(seed.size + 1):l], genome[1: seed.size])
```

**Comment by shuyuzheng** [comment]
Thanks, Ante! You are right, it's a bug in the IR detection function. I've fixed it.

**Comment by ante-turudic** [comment]
Check IRB part, tick has negative value, since line is `tick <- tick - seed.size`. Because of that, changed line should be:
```
genome <- c(genome[(seed.size + 1):l], genome[1: seed.size])
```
